### ISSUE TITLE
4096 character limit

### ISSUE THREAD

**Issue by TJM** [mr-karan/calert#11]
There should probably be an option to "truncate" the message to 4095 characters to prevent this sort of error... alternatively add the same limit and not accept a message that long to pass on?

```
ERR: 2020/04/01 21:53:03 /calert/notification.go:48: Error sending alert Webhook API error: {
  "error": {
    "code": 400,
    "message": "Message is longer than 4096 characters",
    "status": "INVALID_ARGUMENT"
  }
}
```

**Comment by TJM** [comment]
Er, it looks like the code is already in place to handle this, but not released yet?

**Comment by mr-karan** [comment]
Released. https://github.com/mr-karan/calert/releases/tag/v1.2.0
