### ISSUE TITLE
ConfigMap -> Secret

### ISSUE THREAD

**Issue by MPV** [mr-karan/calert#12]
The Google Chat webhook might be consider something to treat as a secret.

What's your view on deploying it as a `kind: Secret` instead of `kind: ConfigMap`?

**Comment by mr-karan** [comment]
I agree. Sorry I don't have bandwidth to fix this myself so feel free to send a PR if you'd like this changed.
Thanks!

**Comment by mr-karan** [comment]
I've decided to no longer support Helm in v2. Sorry about this.
