### ISSUE TITLE
Error sending alert: Message is longer than 4096 characters

### ISSUE THREAD

**Issue by MPV** [mr-karan/calert#17]
Quite often we're getting this error (when there's multiple critical alerts firing), and sadly they don't get propagated due to Google Chat preventing larger messages:

```go
ERR: 2020/05/19 16:01:06 /calert/notification.go:48: Error sending alert Webhook API error: {
  "error": {
    "code": 400,
    "message": "Message is longer than 4096 characters",
    "status": "INVALID_ARGUMENT"
  }
}
ERR: 2020/05/19 16:01:06 /calert/main.go:44: Error while processing request: Error while sending alert
```

Have you also seen this yet? 
Any ideas on solutions/workarounds?

**Comment by mr-karan** [comment]
I believe this solves the issue: https://github.com/mr-karan/calert/pull/10

Have you checked your `max_size` setting?

**Comment by MPV** [comment]
We should fix so the helm chart allows setting that. It doesn't yet: 

https://github.com/mr-karan/calert/blob/master/helm/templates/configmap.yaml

However: isn't it set by default to 4000?

```go
viper.SetDefault("app.max_size", 4000)
```

https://github.com/mr-karan/calert/blob/76c7f170c3482355fc4d33111b753e7e3eec974b/main.go#L73

**Comment by MPV** [comment]
💡 Ah, I see now: the `max_size` feature is not available until [v1.2.0](https://github.com/mr-karan/calert/releases/tag/v1.2.0). 

I'll give that a try (and see if I run into the issues in #15).

**Comment by mr-karan** [comment]
You can try with `v.1.2.1` with a higher value of `app.max_size` if needed and see if that fixes your issue :)

**Comment by MPV** [comment]
Closing as I don't see this with 1.2.x anymore. Thanks! 👍
