### ISSUE TITLE
context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by MPV** [mr-karan/calert#21]
@mr-karan After upgrading to [v1.2.0](https://github.com/mr-karan/calert/releases/tag/v1.2.0), I haven't yet received any alerts, only a log message like this:

`ERR: 2020/05/20 14:42:48 /home/karan/Projects/calert/main.go:44: Error while processing request: Post "https://chat.googleapis.com/v1/spaces/AAAAAAAA11/messages?key=mykeyhere&token=mytokenhere%3D": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

**Comment by MPV** [comment]
@donbowman have you seen this too? (after your changes adding `max_size` in #10)

**Comment by MPV** [comment]
I tried adding [an alert that was always firing](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/alerting.md) and it came through to Google Chat. ✅ 

I'll monitor if this was just a fluke with Google Chat, or if I keep getting this a lot.

**Comment by mr-karan** [comment]
`Client.Timeout exceeded` This likely indicates a problem with the network when reaching to Google Chat servers.

Feel free to reopen if you still face it.
