### ISSUE TITLE
How to alert to google chat room in one thread?

### ISSUE THREAD

**Issue by Huynguyenspkt** [mr-karan/calert#24]
This project is awesome but it now send alert to google chat in many thread.
Could you please support config to send alert in room in 1 thread only?

P/s: Sorry for my bad english

**Comment by mr-karan** [comment]
That entirely depends on how you [group](https://www.prometheus.io/docs/alerting/latest/alertmanager/#grouping) these alerts in Alertmanager. `cAlert` supports batched alerts, so if there are multiple alerts falling under same "group" condition, they will be all delivered in one thread.
