### ISSUE TITLE
reusing threads on alert updates

### ISSUE THREAD

**Issue by jbrouwers** [mr-karan/calert#25]
Wondering if it is possible to send messages concerning the same issue to the same chat thread?

eg. Have the "Resolved" alert go to the same thread as the "Firing" alert.

**Comment by MPV** [comment]
Is this more related to Alertmanager behaviour/features?

See for example this issue where people want the equivalent of this for Slack:
https://github.com/prometheus/alertmanager/issues/2165

**Comment by jbrouwers** [comment]
Yes, looks like it is.

**Comment by goedelsoup** [comment]
I believe this could be feasible within calert with the addition of a template that allows the operator to set the value of [`threadKey`](https://developers.google.com/hangouts/chat/reference/rest/v1/spaces.messages/create#query-parameters) in the request to GChat. Adding a random function to the template's function map and defaulting to it should provide sufficient backwards compatibility. I haven't stepped through the utility of this from the metrics alerting side, but this would suit all of my needs for Loki alerting.

Ideally this would be handled universally by Alertmanager passing an ID but reviewing the state of https://github.com/prometheus/alertmanager/issues/2165 that seems unlikely. With some sufficient docs on avoiding oversaturation of keys, I think this could be a sufficient workaround for most.

**Comment by Jonakss** [comment]
I was thinking about making for example a hash with the start date, instance, alert name,etc. and mapping it with the thread ID returned by the webhook response.
Every time there is a new alert, the hash it's calculated and check the mapping of active alerts.

There are some details to keep in mind, like what if we loose track of an alert (resolved but calert doesn't recive the notification)

I'm doing some test on my workflow (I just starting with Prometheus and Alertmanager)

**Comment by mr-karan** [comment]
Basic threading support is added in v2. Had to work around limitations of Alertmanager not giving a unique ID, but I think the current solution should be fine for 90% usecases.

https://github.com/mr-karan/calert/tree/v2#threading-support-in-google-chat

**Comment by mr-karan** [comment]
Released it in production: https://github.com/mr-karan/calert/blob/main/README.md#threading-support-in-google-chat

Would be interested in feedback, if people try it out.

**Comment by Sarps** [comment]
> Released it in production: https://github.com/mr-karan/calert/blob/main/README.md#threading-support-in-google-chat
> 
> Would be interested in feedback, if people try it out.

Can you add some sample code for this feature please. It's quite difficult following
