### ISSUE TITLE
Publishing helm chart to github pages

### ISSUE THREAD

**Issue by MPV** [mr-karan/calert#32]
In order to consume the helm chart, it needs to be published somewhere. 
GitHub Pages can be used for this.
GitHub Actions can do the publishing, using something like "chart releaser": https://github.com/helm/chart-releaser-action

Would you be up for setting this up?

CR assumes the helm chart is placed in a "charts" directory, so it might involve also moving it into such a subfolder.

**Comment by mr-karan** [comment]
I've actually not had the time to maintain this, since a while. I'm happy to accept a PR for this though.

**Comment by mr-karan** [comment]
I've decided to no longer support Helm in v2. Sorry about this.
