### ISSUE TITLE
How to configure in Rancher Webhooks

### ISSUE THREAD

**Issue by lgaravatti** [mr-karan/calert#33]
Hi guys its the project is Awesome!!  Congrats

But I'm liked to configure in Rancher Webhooks, but i'snt working or I'm not know to configure this, look the images

https://ibb.co/z633pLR
https://ibb.co/dk8JjbZ

Tks

**Comment by mr-karan** [comment]
Hi @lgaravatti 

I'll need some more details on how to reproduce this.
