### ISSUE TITLE
Build latest docker image

### ISSUE THREAD

**Issue by ebrainte** [mr-karan/calert#34]
Hello, first of all, thank you for all you efforts on this great tool!

This is not a real issue, just a reminder if you can publish the latest version of the docker image to dockerhub.
I know the automatic dockerhub buildbot stopped working (because you have to pay now), but you can use github actions to upload the image to dockerhub (for free):
https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

Thank you in advance!

**Comment by mr-karan** [comment]
Hi @ebrainte 

Apologies for not keeping the images updated. I've just pushed a `v1.2.5` (`docker pull mrkaran/calert:v1.2.5`) release which is built from `master` branch. I'll keep this issue open until I setup automatic GitHub Actions here, thanks!

**Comment by ebrainte** [comment]
Thank you for your fast response! :D

**Comment by mr-karan** [comment]
- Releases are automated.
- Instead of Dockerhub, I've switched over to GitHub container registry.

You can find latest docker images of v2 here: https://github.com/mr-karan/calert/pkgs/container/calert
