### ISSUE TITLE
Configuration option is undocumented in the README

### ISSUE THREAD

**Issue by andrewdbate** [mr-karan/calert#35]
The option `app.http_client.proxy_url` is undocumented in the README.

This option is included in the [sample configuration ](https://github.com/mr-karan/calert/blob/master/config.sample.toml) which is included in the released tarball. 

Is it safe to delete this configuration option and rely on its default value if we do not use a proxy?

Many thanks!

**Comment by mr-karan** [comment]
> Is it safe to delete this configuration option and rely on its default value if we do not use a proxy?
Yeah, no need to set that option if you're not using a proxy.

I'll fix the docs.

**Comment by mr-karan** [comment]
Added the option in sample config.

https://github.com/mr-karan/calert/blob/main/config.sample.toml
