### ISSUE TITLE
Configuration option server.socket is ignored

### ISSUE THREAD

**Issue by andrewdbate** [mr-karan/calert#36]
I would like to use calert with a UNIX domain socket.

It is documented in the README that a socket can be specified with the `server.socket` configuration option. 

However, I have grepped through the source code for `socket` and I can see that the value of `server.socket` is only used when it is printed to the log with `sysLog.Printf` and the value is not used for anything else.

I would suggest that either the `server.socket` configuration option is removed (because it currently does nothing), or support should be added so that a domain socket can be used instead of a TCP port.

For example, in an Nginx configuration you can specify the syslog server as either an domain or IP address with an optional port, or alternatively as a UNIX domain socket (see [here](https://nginx.org/en/docs/syslog.html) for the relevant docs). If something similar was implemented here, to use a UNIX domain socket you would write something like `address = "unix:/tmp/calert.sock"` instead of `address = ":6000"`. This would allow a socket to be used instead of a TCP port.

**Comment by mr-karan** [comment]
Good point. I'll review the feasibility of using a socket.

**Comment by mr-karan** [comment]
This option is unused, haven't seen a lot of demand for this feature, doesn't make sense in container environments as well. 
It is removed from the config in v2.

https://github.com/mr-karan/calert/releases/tag/v2.0.0
