### ISSUE TITLE
Log messages should not contain the path of the source files on the build machine

### ISSUE THREAD

**Issue by andrewdbate** [mr-karan/calert#37]
When I run `calert` from the terminal I get log messages such as these (ignoring the `ERR` messages which were due to a typo in my configuration file):
```
$ ./calert
SYS: 2022/01/31 02:44:44 /home/karan/Code/Personal/calert/main.go:154: listening on :6000 | /tmp/calert.sock
ERR: 2022/01/31 02:44:46 /home/karan/Code/Personal/calert/helper.go:26: Error reading template open /etc/calert/message.tmpl: no such file or directory
ERR: 2022/01/31 02:44:46 /home/karan/Code/Personal/calert/main.go:46: Error while processing request: open /etc/calert/message.tmpl: no such file or directory
```

The log messages contain the paths such as `/home/karan/Code/Personal/`. These paths should not be included in the logs. For example, the logs from `alertmanager` do not contain such paths.

Many thanks.

**Comment by mr-karan** [comment]
Will be fixed in next release.

**Comment by mr-karan** [comment]
Fixed with v2: https://github.com/mr-karan/calert/releases/tag/v2.0.0
