### ISSUE TITLE
Update on the project status

### ISSUE THREAD

**Issue by mr-karan** [mr-karan/calert#38]
Firstly, everyone using this project, thanks a lot! It's been a while since I've worked on this code-base since my original needs were met on v1 and I've just gotten busy with other things. This was also kind of my first _bigger_ OSS codebase in Golang when I initially started working 3 years back.

I've a lot to improve in terms of docs/semantics and I'm planning for a full rewrite major version (v2). Stuff I've in mind:

- Add metrics to the library itself, so users can see how many alerts were sent/errors etc.
- Use koanf instead of viper and make existing config easier
- Use providers package interface for notifications. I am thinking to extend `cAlert` beyond Google Chat and add Rocketchat support as well. I'll have to do a feasibility check on this, but with this change, I'll be happy to accept PRs for other notification providers as well if someone's interested in.
- Automated releases using GitHub Actions
- And ofcourse, cleanup the code structure :)

I expect a v2 alpha at-least by end of February. If there's a feature you'd like to see, please mention it here and I'll add in my roadmap if it's feasible for me to implement.

Thanks!

**Comment by MPV** [comment]
Thanks for sharing, cool that you’re still working on it. 

Metrics sounded promising! 🤞

**Comment by mr-karan** [comment]
I've been running `v2` in production since the last few days and haven't found any issues. Merging to the stable branch.
