### ISSUE TITLE
BUG: Config from Env-Variables

### ISSUE THREAD

**Issue by R-Studio** [mr-karan/calert#40]
Hi @mr-karan thanks for your great project.
I think I noticed a little bug and documentation typo:
- Bug: I was not able to use it with environment variables. I think calert searches always the config-file because I constantly get the error `panic: open config.sample.toml: no such file or directory` even If I set the env-vars.
- Doc: In the documentation the prefix is `CALERT_` but in the codes it looks like the prefix should be `CALERTS_`. (I am not a Go programmer, so excuse me if i am wrong.)

**Comment by mr-karan** [comment]
@R-Studio Thanks. Both are valid, fix will be released soon.

**Comment by mr-karan** [comment]
Please try out the latest release v2.0.2: https://github.com/mr-karan/calert/releases/tag/v2.0.2

**Comment by R-Studio** [comment]
@mr-karan WOOOW you are fast ⚡
I get an error but it works:
![image](https://user-images.githubusercontent.com/7498854/159326186-95d1b425-a047-4817-81a6-a7a7f4bb48b4.png)

**Comment by mr-karan** [comment]
Yeah it's logged as a warning.
