### ISSUE TITLE
Problem acknowledging active alerts and creating flood in channels

### ISSUE THREAD

**Issue by SergioIbIGZ** [mr-karan/calert#41]
Hello Mr. Karan :)

I am using calert 2.0.2 in my kube-prometheus-stack deployment (31.0.0) to send the alerts from alertmanager to Google Chat receivers. 
I use the prometheus-telegram-bot 1.0.0. as well.

Google Chat receivers works properly with 99% alerts/rules, but I have a problem with an specific alertmanager rule:

![image](https://user-images.githubusercontent.com/102799006/161504390-cd02515d-2d5c-46f2-8ab8-114cb89e2c08.png)

`    - alert: CollectorsMetricsInputInfo 
      expr: sum by (collector, namespace, component, container) (round(increase(collector_inputcount[4h]))) == 0
      for: 24h
      labels:
        severity: info
{{- if .Values.kubeprometheusstack.defaultRules.additionalRuleLabels }}
{{ toYaml .Values.kubeprometheusstack.defaultRules.additionalRuleLabels | indent 8 }}
{{- end }}
      annotations:
        summary: Collector pod did not receive messages for 4 hours
        message: Collector {{`{{`}}$labels.container{{`}}`}} in namespace {{`{{`}}$labels.namespace{{`}}`}} from {{`{{`}}$labels.component{{`}}`}} has NO INPUT messages since 4 hours ago.`

This rule give me alerts like this:

![collectorinfoalerts](https://user-images.githubusercontent.com/102799006/161504536-6d172ffa-9293-4a6f-9616-b671c60c5403.png)

As I said, these rule/alerts works properly with Telegram receivers, but not with Google Chat. In Google Chat, I get a huge flood of the same alert message repeating (maybe 100 in a row, in less than 5 minutes), continuously, some with "resolved" status, but most like "firing".

![gchatalertscollector](https://user-images.githubusercontent.com/102799006/161504722-f714874c-9277-4e73-b71c-6df0055dca6c.png)

The only way to avoid that flood is to silence this alerts in AlertManager.

Meanwhile, the behavior with prometheus-telegram-bot is normal.

To me, it looks related to the way to identify what alert is new and what is not, or their fingerprint, according to https://github.com/mr-karan/calert/issues/25, but I am unable to see what is wrong with this kind of rule.

A few calert pod logs; I don't see anything strange on it; but you can see how is dispatching new messages to the chat almost each 30 seconds, and always the same alerts:

2022/04/04 06:29:59 [google-chat-bot-7fc5cfb54-f5ngv/krB1cViUTd-010859] "POST http://google-chat-bot:6000/dispatch HTTP/1.1" from 110.124.152.4:34410 - 200 40B in 7.066438793s
time="2022-04-04T06:29:59Z" level=info msg="dispatching new alert" receiver=default-alertmanager-config-alert-info 
time="2022-04-04T06:29:59Z" level=info msg="dispatching alerts" count=10
time="2022-04-04T06:29:59Z" level=info msg="dispatching alerts to google chat" count=10

2022/04/04 06:30:05 [google-chat-bot-7fc5cfb54-f5ngv/krB1cViUTd-010860] "POST http://google-chat-bot:6000/dispatch HTTP/1.1" from 110.124.152.4:34482 - 200 40B in 6.447221446s
time="2022-04-04T06:30:05Z" level=info msg="dispatching new alert" receiver=default-alertmanager-config-alert-info
time="2022-04-04T06:30:05Z" level=info msg="dispatching alerts" count=10
time="2022-04-04T06:30:05Z" level=info msg="dispatching alerts to google chat" count=10

2022/04/04 06:30:11 [google-chat-bot-7fc5cfb54-f5ngv/krB1cViUTd-010861] "POST http://google-chat-bot:6000/dispatch HTTP/1.1" from 110.124.152.4:34578 - 200 40B in 6.297160372s
time="2022-04-04T06:30:11Z" level=info msg="dispatching new alert" receiver=default-alertmanager-config-alert-info
time="2022-04-04T06:30:11Z" level=info msg="dispatching alerts" count=10
time="2022-04-04T06:30:11Z" level=info msg="dispatching alerts to google chat" count=10

 
Would you be so kind to guide me on what might be going on?
I would like these alerts to reach both, Telegram and Google Chat, but the flood makes the Google chat channel unusable.

If you need any extra information please let me know.

A lot of thanks!!! :)

**Comment by weibo-zhao** [comment]
I have met the same problem when using v2.0.2. I got message flood even though I have configure the parameters of Alertmanager:

Pod logs from calert.
time="2022-05-04T06:48:35Z" level=info msg="attempting to load config from file" path=/app/static/config.toml
time="2022-05-04T06:48:35Z" level=info msg="attempting to read config from env vars"
time="2022-05-04T06:48:35Z" level=info msg="initialised provider" room=dev_alerts
time="2022-05-04T06:48:35Z" level=info msg="initialised provider" room=nextcloud_alert
time="2022-05-04T06:48:35Z" level=info msg="initialised provider" room=prod_alerts
time="2022-05-04T06:48:35Z" level=info msg="booting calert" version="v2.0.2 (268e712 2022-03-21T15:28:07Z)"
time="2022-05-04T06:48:35Z" level=info msg="starting http server" addr=":6000"
2022/05/04 06:49:30 [calert-6fd5fb5656-54qlt/iu6oLfMSLN-000001] "GET http://10.216.196.253:6000/ping HTTP/1.1" from 185.48.116.242:46916 - 200 34B in 113.01µs
2022/05/04 06:49:30 [calert-6fd5fb5656-54qlt/iu6oLfMSLN-000002] "GET http://10.216.196.253:6000/ping HTTP/1.1" from 185.48.116.242:46918 - 200 34B in 271.104µs
time="2022-05-04T06:50:17Z" level=info msg="dispatching new alert" receiver=nextcloud_alert
time="2022-05-04T06:50:17Z" level=info msg="dispatching alerts" count=5
time="2022-05-04T06:50:17Z" level=info msg="dispatching alerts to google chat" count=5
2022/05/04 06:50:26 [calert-6fd5fb5656-54qlt/iu6oLfMSLN-000003] "POST http://calert:6000/dispatch HTTP/1.1" from 10.216.196.251:45536 - 200 40B in 8.635120505s
2022/05/04 06:50:30 [calert-6fd5fb5656-54qlt/iu6oLfMSLN-000004] "GET http://10.216.196.253:6000/ping HTTP/1.1" from 185.48.116.242:48270 - 200 34B in 38.43µs
2022/05/04 06:50:30 [calert-6fd5fb5656-54qlt/iu6oLfMSLN-000005] "GET http://10.216.196.253:6000/ping HTTP/1.1" from 185.48.116.242:48272 - 200 34B in 23.137µs
time="2022-05-04T06:51:06Z" level=info msg="dispatching new alert" receiver=nextcloud_alert
time="2022-05-04T06:51:06Z" level=info msg="dispatching alerts" count=5
time="2022-05-04T06:51:06Z" level=info msg="dispatching alerts to google chat" count=5
2022/05/04 06:51:14 [calert-6fd5fb5656-54qlt/iu6oLfMSLN-000006] "POST http://calert:6000/dispatch HTTP/1.1" from 10.216.196.251:46614 - 200 40B in 7.39941931s

Alertmanager config:

alertmanager:
  config:
    global: {}
    receivers:
      - name: "nextcloud_alert"
        webhook_configs:
          - url: "http://calert:6000/dispatch"
    route:
      receiver: "nextcloud_alert"
      routes:
        - receiver: "nextcloud_alert"
          group_by: ['alertname']
          group_interval: "5m"
          match:
            severity: "critical"

**Comment by weibo-zhao** [comment]
I have read the go code carefully.
1. There seems to be a Typo here related to "[loookup](https://github.com/mr-karan/calert/blob/3533aee63f651051fea90d6ccb39a6b77a2408c9/internal/providers/google_chat/google_chat.go#L104)".

**Comment by weibo-zhao** [comment]
> @weibo-zhao and @SergioIbIGZ Thanks for spending time on this issue. Just wanted to post an update that I've read the comments, will need a bit of time to fix this bug as I want to reproduce this in my local environment as well.

Thanks a lot!

**Comment by weibo-zhao** [comment]
Hi there, our team have found out the problem. It is because that the timeout values are set too short. The following are our change to the default values in config.sample.toml.

[app]
...
server_timeout = "5s" # Server timeout for HTTP requests.
...

[providers.prod_alerts]
...
timeout = "7s" # Timeout for making requests to Provider.
...
The reason behind is to alertmanager takes some time for the POST request. Just as the following pod log shows as example:

2022/05/04 06:50:26 [calert-6fd5fb5656-54qlt/iu6oLfMSLN-000003] "POST http://calert:6000/dispatch HTTP/1.1" from 10.216.196.251:45536 - 200 40B in 8.635120505s

It takes around 8.6s, which is greater than server_timeout and timeout. That means the alertmanager notices that the connection between calert and itself are interrupted because of timeout, so it will always try to repeat to send the alerts again and again. That will explain why we get message flood in channels.

The v2.0.2 image itself works well in our system now and Mr. Karan Sharma you don't need to change the code. @SergioIbIGZ @mr-karan

**Comment by mr-karan** [comment]
@weibo-zhao That is great. I'll update the default config to more reasonable defaults.
