### ISSUE TITLE
Publish the chart to a helm registry / ArtifactHub

### ISSUE THREAD

**Issue by aslafy-z** [mr-karan/calert#48]
We'd like to deploy calert using the helm terraform provider.
This provider requires "built" helm charts, published within a helm registry.
Publishing the chart can be done within a github action and targeted to the gh-pages branch which can be exposed as a Github pages directory. ref: https://github.com/marketplace/actions/helm-chart-releaser

**Comment by mr-karan** [comment]
PR is appreciated. `helm` chart is community maintained.
