### ISSUE TITLE
Error parsing values

### ISSUE THREAD

**Issue by JPFreeski** [mr-karan/calert#55]
Greetings and pardon my lack of knowledge with go.

I'm receiving an endless stream of errors regarding the message.tmpl 

`ERR: 2023/01/02 16:10:45 /home/karan/Code/Personal/calert/main.go:46: Error while processing request: template: message.tmpl:1:78: executing "message.tmpl" at <toUpper>: invalid value; expected string`

I'm using the example provided and wondering why the error when parsing `toUpper`

Here's my message.tmpl

```
*{{ .Labels.alertname | Title }} - {{.Status | Title }} ({{.Labels.severity | toUpper }})*
{{ range .Annotations.SortedPairs -}}
{{ .Name }}: {{ .Value}}
{{ end -}}
```
Any help would be appreciated!

**Comment by mr-karan** [comment]
Duplicate: https://github.com/mr-karan/calert/issues/54

**Comment by JPFreeski** [comment]
Thank you!
