### ISSUE TITLE
What is the url of the helm chart repository?

### ISSUE THREAD

**Issue by bautistamad** [mr-karan/calert#56]
This is not an issue, it's just a question but I couldn't find where to raise a discussion, I would like to know what is the url of the chart to display it or is it only allowed manually?

**Comment by mr-karan** [comment]
Sorry, I don't use `helm` but a quick look at docs showed me that you can add the GH repo URL directly?

```
helm repo add calert https://github.com/mr-karan/calert/tree/main/contrib/helm
helm repo update
```

would this work? 

cc @weibo-zhao would you know?

**Comment by aslafy-z** [comment]
#50 will allow the following:
```
helm repo add calert https://mr-karan.github.io/calert/charts
helm repo update
```

**Comment by aslafy-z** [comment]
Duplicate #48

**Comment by mr-karan** [comment]
Closing. https://github.com/mr-karan/calert/issues/48 is merged
