### ISSUE TITLE
[Feature request] - Google Chat cards

### ISSUE THREAD

**Issue by alex5517** [mr-karan/calert#58]
Hi, 

Have you considered adding support for Cards in Google Chat? 

https://developers.google.com/chat/api/reference/rest/v1/cards

**Comment by mr-karan** [comment]
Personally think that for information which has text content, cards aren't useful. 

https://github.com/mr-karan/calert/issues/43

**Comment by alex5517** [comment]
Alright, i just find that in some cases it makes the text more humanly readable.
