### ISSUE TITLE
Error msg="error dispatching alerts" error="no provider configured for room: calert"

### ISSUE THREAD

**Issue by avivlev98** [mr-karan/calert#59]
Hi , First I wanted to thank you for creating the helm chart and writing this useful project .
I have an issue when i try to integrate the calert with alertmanager I use kube-prometheus-stack helm chart , im getting this error at the calert pod logs : **level=error msg="error dispatching alerts" error="no provider configured for room: calert"**

this is the error im getting in alertmanager pod logs : **receiver=calert integration=webhook[0] msg="Notify attempt failed, will retry later" attempts=1 err="unexpected status code 500: http://calert:6000/dispatch"** 

here is the calert chart values : 

app:
  address: "0.0.0.0:6000" # Address of the HTTP Server.
  server_timeout: "60s" # Server timeout for HTTP requests.
  enable_request_logs: true # Whether to log incoming HTTP requests or not.
  log: "debug" # Use `debug` to enable verbose logging. Can be set to `info` otherwise.

providers: 
  prod_alerts:
    type: "google_chat" # Type of provider. Currently supported value is `google_chat`.
    endpoint: "https://chat.googleapis.com/v1/spaces/My_space/messages?key=key&token=token%3D" # Google Chat Webhook URL
    max_idle_conns:  50 # Max idle connections in the HTTP Client.
    timeout: "30s" # Timeout for making requests to Provider.
    #proxy_url: "http://internal-squid-proxy.com:3128" # Specify `proxy_url` as your proxy endpoint to route all HTTP requests to the provider via a proxy.
    template: "static/message.tmpl" # Path to specify the message template path.
    thread_ttl: "12h" # Timeout to keep active alerts in memory. Once this TTL expires, a new thread will be created.
    dry_run: false

templates: 
  message.tmpl: |
    *({{.Labels.severity | toUpper }}) {{ .Labels.alertname | Title }} - {{.Status | Title }}*
    {{ range .Annotations.SortedPairs -}}
    {{ .Name | Title }}: {{ .Value}}
    {{ end -}}

args:
- "--config=/app/static/config.toml"

service:
  type: ClusterIP
  port: 6000

**here is the alertmanager chart values** : 

alertmanager:

  enabled: true

  apiVersion: v2

  config:
    global:
      resolve_timeout: 5m
    inhibit_rules:
      - source_matchers:
          - 'severity = critical'
        target_matchers:
          - 'severity =~ warning|info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'severity = warning'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'alertname = InfoInhibitor'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
    route:
      group_by: ['namespace']
      group_wait: 30s
      group_interval: 60s
      repeat_interval: 3h
      receiver: 'calert'
      routes:
      - receiver: 'null'
        matchers:
          - alertname =~ "InfoInhibitor|Watchdog"
      - receiver: 'calert'
    receivers:
    - name: 'null'
    - name: 'calert'
      webhook_configs:
      - url: 'http://calert:6000/dispatch'
    templates:
    - '/etc/alertmanager/config/*.tmpl'
    
I would be happy to receive direction on how to solve this error thank you .

**Comment by G900** [comment]
I think you are missing  `calert` configuration in your providers section, you have only `prod_alerts`.

**Comment by avivlev98** [comment]
> I think you are missing `calert` configuration in your providers section, you have only `prod_alerts`.

I notice that the rest of the configuration is a definition of additional spaces for other notifications like `dev_alerts` and `qa_alerts` , do I have to set them to make `calert` work?

**Comment by G900** [comment]
The receiver specified in alertmanager chart values should have the corresponding config in calert chart values.
In your case you specified `calert` receiver in alertmanager, but you are missing calert configuration.

**Comment by mr-karan** [comment]
Yup, thanks for explaining @G900 

Those providers have to be configured in `config.toml`.

**Comment by avivlev98** [comment]
> The receiver specified in alertmanager chart values should have the corresponding config in calert chart values. In your case you specified `calert` receiver in alertmanager, but you are missing calert configuration.
> 
> ```
> providers:
> prod_alerts:
> type: "google_chat" 
> endpoint: ""
> ..
> dev_alerts:
> type: "google_chat" 
> endpoint: ""
> ..
> qa_alerts:
> type: "google_chat" 
> endpoint: ""
> ..
> calert:
> type: "google_chat" 
> endpoint: ""
> ...
> ```
> 
> From documentaion:
> 
> > Here's an example of how Alertmanager config looks like. Notice the value of receiver (prod_alerts) should match one of provider.<room_name> (eg provider.prod_alerts) in your config.toml):



> Yup, thanks for explaining @G900
> 
> Those providers have to be configured in `config.toml`.

Thank you very much , after I changed the values in alertmanager to match the `receiver` with `prod_alerts` it worked I started to get alerts .
this is the final values that work for me : 

calert chart values :

app:
address: "0.0.0.0:6000" # Address of the HTTP Server.
server_timeout: "60s" # Server timeout for HTTP requests.
enable_request_logs: true # Whether to log incoming HTTP requests or not.
log: "debug" # Use debug to enable verbose logging. Can be set to info otherwise.

providers:
prod_alerts:
type: "google_chat" # Type of provider. Currently supported value is google_chat.
endpoint: "https://chat.googleapis.com/v1/spaces/My_space/messages?key=key&token=token%3D" # Google Chat Webhook URL
max_idle_conns: 50 # Max idle connections in the HTTP Client.
timeout: "30s" # Timeout for making requests to Provider.
#proxy_url: "http://internal-squid-proxy.com:3128/" # Specify proxy_url as your proxy endpoint to route all HTTP requests to the provider via a proxy.
template: "static/message.tmpl" # Path to specify the message template path.
thread_ttl: "12h" # Timeout to keep active alerts in memory. Once this TTL expires, a new thread will be created.
dry_run: false

templates:
message.tmpl: |
({{.Labels.severity | toUpper }}) {{ .Labels.alertname | Title }} - {{.Status | Title }}
{{ range .Annotations.SortedPairs -}}
{{ .Name | Title }}: {{ .Value}}
{{ end -}}

args:

"--config=/app/static/config.toml"
service:
type: ClusterIP
port: 6000


Alertmanager values chart : 

`alertmanager:

  ## Deploy alertmanager
  ##
  enabled: true

  apiVersion: v2

  config:
    global:
      resolve_timeout: 5m
    inhibit_rules:
      - source_matchers:
          - 'severity = critical'
        target_matchers:
          - 'severity =~ warning|info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'severity = warning'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'alertname = InfoInhibitor'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
    route:
      group_by: ['namespace']
      group_wait: 30s
      group_interval: 60s
      repeat_interval: 3h
      receiver: 'prod_alerts'
      routes:
      - receiver: 'null'
        matchers:
          - alertname =~ "InfoInhibitor|Watchdog"
      - receiver: 'prod_alerts'
    receivers:
    - name: 'null'
    - name: 'prod_alerts'
      webhook_configs:
      - url: 'http://calert:6000/dispatch'
    templates:
    - '/etc/alertmanager/config/*.tmpl'`
