### ISSUE TITLE
Referencing attributes from alertmanager payload in message.tmpl

### ISSUE THREAD

**Issue by G900** [mr-karan/calert#60]
Hello, given that the alert manager payload looks [like this](https://prometheus.io/docs/alerting/latest/configuration/#webhook_config):

```
{
  "version": "4",
  "groupKey": [<string>](https://prometheus.io/docs/alerting/latest/configuration/#string),              // key identifying the group of alerts (e.g. to deduplicate)
  "truncatedAlerts": [<int>](https://prometheus.io/docs/alerting/latest/configuration/#int),          // how many alerts have been truncated due to "max_alerts"
  "status": "<resolved|firing>",
  "receiver": [<string>](https://prometheus.io/docs/alerting/latest/configuration/#string),
  "groupLabels": <object>,
  "commonLabels": <object>,
  "commonAnnotations": <object>,
  "externalURL": [<string>](https://prometheus.io/docs/alerting/latest/configuration/#string),           // backlink to the Alertmanager.
  "alerts": [
    {
      "status": "<resolved|firing>",
      "labels": <object>,
      "annotations": <object>,
      "startsAt": "<rfc3339>",
      "endsAt": "<rfc3339>",
      "generatorURL": [<string>](https://prometheus.io/docs/alerting/latest/configuration/#string),      // identifies the entity that caused the alert
      "fingerprint": [<string>](https://prometheus.io/docs/alerting/latest/configuration/#string)        // fingerprint to identify the alert
    },
    ...
  ]
}
```

How can I reference  `commonAnnotations` or `externalURL` inside message.tmpl file?

**Comment by mr-karan** [comment]
You can edit the [default](https://github.com/mr-karan/calert/blob/main/static/message.tmpl) template and access those values with `{{. commonAnnotations}}` and `{{.externalURL}}`

**Comment by G900** [comment]
@mr-karan 
I have this template:
```
*[{{.Status | toUpper }}] {{ .Labels.alertname | Title }}*
externalURL: {{.externalURL}}
```
And calert fails with this message:
```
 level=error msg="Error parsing values in template" error="template: message.tmpl:2:15: executing \"message.tmpl\" at <.externalURL>: can't evaluate field externalURL in type template.Alert"
```

**Comment by mr-karan** [comment]
@G900 My bad. Actually cAlert uses the [Alert](https://github.com/prometheus/alertmanager/blob/main/template/template.go#L304) struct defined in `alertmanager` itself. You'll have to check which field here exposes `externalURL`.

**Comment by G900** [comment]
Do I understand it correctly,  that `message.tmpl`  i a type of  Alert struct, and there is no way to reference Data struct from `message.tmpl`, because the Data struct is parent to Alert?

**Comment by G900** [comment]
I might have found the answer to the above question [here](https://github.com/mr-karan/calert/blob/c92b2bbf2d197e23999ff004cbfd9d1a8ea910d2/internal/providers/google_chat/message.go#L21).

**Comment by danksim** [comment]
`.` should be `$root`, no? Or else, we only have access to individual `Alert` structs and cannot add the Alertmaanger link using `.ExternalURL` and `.Receiver`.
