### ISSUE TITLE
Gchat thread doesn't works

### ISSUE THREAD

**Issue by akolacz** [mr-karan/calert#61]
Hi,

Yesterday i did mutiple tests and i have upgraded the version of calert to 2.0.6 to test the new functionality of gchat thread like the following example :

![image](https://user-images.githubusercontent.com/19993116/233634623-a78c3717-b69f-4db7-903e-236b278405c6.png)

but when i have tried to do this with calert and gchat in thread channel gchat (same channel like the example above) it's doesn't works : 

![image](https://user-images.githubusercontent.com/19993116/233638281-41b7d177-d3ff-478c-af64-2270b6df8dae.png)

our configuration alertmanager : 

![image](https://user-images.githubusercontent.com/19993116/233639983-33fd5d44-a756-4cd6-845f-29093d23595b.png)

our configuration calert : 

![image](https://user-images.githubusercontent.com/19993116/233640509-14f59324-202e-417b-adf7-c46b92823ddb.png)

              
We have try to change the group by to this : 

`- receiver: 'google-chat'
                  group_by: [...]
                  matchers:
                    - severity =~ "warning|critical"`
                    
but nothing changed 

if you have any idea or this not yet impleted in calert for this functionality or if it's need a specific configuration. 

thank you in advance.

**Comment by mr-karan** [comment]
GChat Threads is a new feature which [only works for spaces created after March 15 2023](https://workspaceupdates.googleblog.com/2023/02/new-google-chat-spaces-will-be-in-line-threaded.html). I've not had a chance to test them and the same isn't available on cAlert yet.

**Comment by paulelie** [comment]
@mr-karan @Nakada78 FYI, it works out of the box by adding `&messageReplyOption=REPLY_MESSAGE_FALLBACK_TO_NEW_THREAD` to the endpoint property.

https://developers.google.com/chat/how-tos/webhooks#start_or_reply_to_a_message_thread

**Comment by mr-karan** [comment]
@paulelie Nice spot. Thanks a lot. I'll make the changes to `cAlert` to add this option shortly.

**Comment by mr-karan** [comment]
This is done. https://github.com/mr-karan/calert/releases/tag/v2.1.1

https://github.com/mr-karan/calert/issues/74#issuecomment-1993611015
