### ISSUE TITLE
error preparing message" error="template: message.tmpl: \"message.tmpl\" is an incomplete or empty template

### ISSUE THREAD

**Issue by pradeep6** [mr-karan/calert#66]
I have implemented the helm chart based out of the repo and getting this error whenever alert manager is trying to dispatch an alert. Can you please provide me any help and below is the mentioned error.

time="2023-05-31T14:15:13Z" level=error msg="Error parsing values in template" error="template: message.tmpl: \"message.tmpl\" is an incomplete or empty template"
time="2023-05-31T14:15:13Z" level=error msg="error preparing message" error="template: message.tmpl: \"message.tmpl\" is an incomplete or empty template"

$ cat message.tmpl (Output from the pod)
*({{.Labels.severity | toUpper }}) {{ .Labels.alertname | Title }} - {{.Status | Title }}*
{{ range .Annotations.SortedPairs -}}
{{ .Name | Title }}: {{ .Value}}
{{ end -}}

**Comment by mr-karan** [comment]
As the error suggest, I think the template is not mounted correctly, or the config.toml is not configured to locate for it.

**Comment by whenckemaier** [comment]
@pradeep6 I have the same problem, did you manage to solve it?
