### ISSUE TITLE
JSON special characters show up escaped

### ISSUE THREAD

**Issue by wagdav** [mr-karan/calert#7]
Hi @mr-karan, 
Thanks for making calert, we just deployed it at Pix4D and we're really happy with it!

We noticed the following issue. Take an alert where, for example, the summary field contains `"` characters:
```
# test-payload.json
{
    "alerts": [
        {
            "status": "firing",
            "annotations": {
                "summary": "Server \"foo\" is down"
            }
        }
    ]
}
```

Now send this to calert

```
curl -XPOST -d @test-payload.json http://localhost:6000/create?room_name=test -i
```

The following message shows up in the targeted Hangouts Chat channel (using the default message template):

```
summary: Server &#34;foo&#34; is down
```

In this case, I'd expect the double quotes to be kept and not escaped.

**Comment by mr-karan** [comment]
@wagdav Thanks for reporting. I'll investigate this.

**Comment by wagdav** [comment]
@mr-karan  Did you have a chance to take a look at this?

If you could point me to a place in the code where the problem could happen I could try to submit a PR with a fix. 

Thanks!

**Comment by mr-karan** [comment]
@wagdav Been caught up with some things, my bad. Feel free to take this up 

This is the part where I try to decode the alertmanager payload:
https://github.com/mr-karan/calert/blob/master/api.go#L95

Over here, is when I transform this payload to what Google Chat expects:
https://github.com/mr-karan/calert/blob/master/api.go#L100

I guess we should check for unescaped characters while populating the template, which is here:
https://github.com/mr-karan/calert/blob/6eabd823f2bd18ecae09739f60c13d9e5d41e3ee/helper.go#L29
