### ISSUE TITLE
InvalidValue Error in Template

### ISSUE THREAD

**Issue by AshishDahiyaVlink** [mr-karan/calert#72]
Hi,

Thanks for your great work.I am trying to Implement calert with prometheus alertmanager. I am getting following error when alertmanager pushed alert to calert

ERROR[2024-02-16T09:59:13Z] Error parsing values in template              error="template: message.tmpl:1:78: executing \"message.tmpl\" at <toUpper>: invalid value; expected string"
ERROR[2024-02-16T09:59:13Z] error preparing message                       error="template: message.tmpl:1:78: executing \"message.tmpl\" at <toUpper>: invalid value; expected string"

It will be great if you can guide me

**Comment by mr-karan** [comment]
The default template expects a few labels: https://github.com/mr-karan/calert/blob/main/static/message.tmpl

You can give a custom template in config: https://github.com/mr-karan/calert/blob/main/config.sample.toml#L13
