### ISSUE TITLE
Option to disable threading in 2.1.x

### ISSUE THREAD

**Issue by brosef** [mr-karan/calert#74]
Message threading is causing us to miss some alerts, so we've had to roll back to v2.0.7. Would it be possible to add a config option to disable threading?

**Comment by mr-karan** [comment]
Hi @brosef . You can use v2.1.1. The default behavior is threading is disabled. In the `config.toml`, you can use the following config to enable threaded replies:

```
threaded_replies = true # Whether to send threaded replies or not.
```

Hope this helps.
